# use babel
# parser: babel-eslint

# root
root: true

# code env
env:
  node: true
  mocha: true

# rules
rules:
  # basic
  semi: [2, always] # ;
  indent: [2, 2]
  quotes: [2, single] # '' | ""
  eqeqeq: 2 # ===
  camelcase: 2
  radix: 2 # parseInt('100', 10)
  yoda: 2 # 'blue' === sky
  no-var: 2 # ES6 let & const
  no-const-assign: 2
  strict: [2, global] # 'use strict'

  # 大括号
  curly: [2, multi-line] # 需要大括号
  brace-style: 2 # 左大括号同一行

  # disable default
  no-unused-vars: 0 # 已定义, 未使用
  no-console: 0 # console

  # space
  # 有 jsbeautify 保持风格

parserOptions:
  ecmaVersion: 6

extends: 'eslint:recommended'